export const getPreviewStyles = () => `
<style>
  body { margin: 0; }
  .preview-doc { font-family: 'Inter', sans-serif; line-height: 1.6; color: #1a1a2e; }
  .preview-doc.theme-dark { background: #1a1a2e; color: #f5f5f5; }
  .preview-doc.theme-sepia { background: #f5f0e8; color: #433422; }
  .preview-doc.theme-minimal { background: #fff; color: #000; font-family: 'Courier New', monospace; }
  .preview-doc.theme-light { background: #fff; color: #111; }
  
  .chat-header { margin-bottom: 30px; border-bottom: 2px solid rgba(0,0,0,0.1); padding-bottom: 20px; }
  .preview-doc.theme-dark .chat-header { border-bottom-color: rgba(255,255,255,0.1); }
  
  .chat-title { font-family: 'Syne', sans-serif; font-size: 2.2rem; font-weight: 800; margin: 0 0 10px 0; }
  .chat-meta { font-size: 0.85rem; color: #666; display: flex; gap: 15px; }
  .preview-doc.theme-dark .chat-meta { color: #aaa; }
  
  .msg-block { margin-bottom: 28px; padding-bottom: 16px; border-bottom: 1px solid rgba(0,0,0,0.05); }
  .preview-doc.theme-dark .msg-block { border-bottom-color: rgba(255,255,255,0.05); }
  .msg-block:last-child { border-bottom: none; }
  
  .msg-header { display: flex; align-items: baseline; gap: 10px; margin-bottom: 8px; }
  .msg-role { font-weight: 700; font-size: 1.05rem; }
  .msg-role.user { color: #6c63ff; }
  .msg-role.assistant { color: #ff4d85; }
  .msg-time { font-size: 0.75rem; color: #999; }
  
  .msg-body { font-size: 0.95rem; }
  .msg-body p { margin: 0 0 12px 0; }
  .msg-body p:last-child { margin: 0; }
  .msg-body h1 { font-size: 1.2rem; font-weight: 800; margin: 16px 0 8px; }
  .msg-body h2 { font-size: 1.05rem; font-weight: 700; margin: 12px 0 6px; }
  .msg-body h3 { font-size: 0.92rem; font-weight: 700; margin: 10px 0 6px; }
  .msg-body ul, .msg-body ol { padding-left: 18px; margin-bottom: 8px; }
  .msg-body li { margin-bottom: 3px; }
  
  .msg-body pre { background: rgba(0,0,0,0.06); border: 1px solid rgba(0,0,0,0.1); border-radius: 8px; padding: 12px 14px; overflow-x: auto; font-family: 'JetBrains Mono', monospace; font-size: 0.78rem; margin: 8px 0; white-space: pre-wrap; word-break: break-all; }
  .preview-doc.theme-dark .msg-body pre { background: rgba(255,255,255,0.04); border-color: rgba(255,255,255,0.07); }
  
  .msg-body code { font-family: 'JetBrains Mono', monospace; font-size: 0.8em; background: rgba(108,99,255,0.1); border-radius: 4px; padding: 1px 4px; }
  .msg-body pre code { background: none; padding: 0; }
  
  .msg-body table { width: 100%; border-collapse: collapse; font-size: 0.83rem; margin: 10px 0; }
  .msg-body th { background: rgba(108,99,255,0.1); font-weight: 700; }
  .msg-body th, .msg-body td { border: 1px solid rgba(0,0,0,0.1); padding: 7px 10px; text-align: left; }
  .preview-doc.theme-dark .msg-body th, .preview-doc.theme-dark .msg-body td { border-color: rgba(255,255,255,0.09); }
  
  .msg-divider { border: none; border-top: 1px solid rgba(0,0,0,0.07); margin: 16px 0; }
  .preview-doc.theme-dark .msg-divider { border-top-color: rgba(255,255,255,0.06); }
  
  .msg-body blockquote { border-left: 3px solid #6c63ff; margin: 10px 0; padding: 8px 14px; background: rgba(108,99,255,0.05); border-radius: 0 6px 6px 0; }
</style>
`;

export function getThemeBG(theme) {
  return { dark: '#1a1a2e', sepia: '#f5f0e8', minimal: '#ffffff', light: '#ffffff' }[theme] || '#ffffff';
}

function countWords(str) {
  return str.trim().split(/\s+/).filter(w => w.length > 0).length;
}

export function buildDocumentHTML(messages, options, markedInstance) {
  const theme = options.theme || 'light';
  const now = new Date().toLocaleString();
  const words = messages.reduce((n, m) => n + countWords(m.content), 0);
  
  let html = `<div class="preview-doc theme-${theme}"><div style="padding:40px;">`;
  
  html += `
    <div class="chat-header">
      <h1 class="chat-title">AI Conversation Export</h1>
      <div class="chat-meta">
        <span>Generated by ChatExport Pro</span>
        <span>•</span>
        <span>${now}</span>
      </div>
  `;

  if (options.stats) {
    html += `
      <div style="margin-top:12px;font-size:0.85rem;opacity:0.8;">
        <strong>Stats:</strong> ${messages.length} messages | ${words.toLocaleString()} words | ~${Math.round(words * 1.33).toLocaleString()} tokens
      </div>
    `;
  }
  html += `</div>`;

  if (options.toc) {
    html += `<div class="msg-block" style="background:rgba(108,99,255,0.05);padding:16px;border-radius:12px;">`;
    html += `<h2 style="margin:0 0 10px 0;font-size:1.1rem;">Table of Contents</h2><ul style="margin:0;padding-left:20px;font-size:0.9rem;">`;
    messages.forEach((msg, i) => {
      if (msg.role !== 'system') {
        const snippet = msg.content.substring(0, 40).replace(/\\n/g, ' ') + '...';
        html += `<li><a href="#msg-${i}" style="color:inherit;text-decoration:none;">${msg.name}: ${snippet}</a></li>`;
      }
    });
    html += `</ul></div>`;
  }

  messages.forEach((msg, i) => {
    if (msg.role === 'system') return;
    const ts = (options.timestamps && msg.timestamp) ? `<span class="msg-time">${msg.timestamp}</span>` : '';
    const parsedBody = markedInstance.parse(msg.content);
    
    html += `
      <div class="msg-block" id="msg-${i}">
        <div class="msg-header">
          <span class="msg-role ${msg.role}">${msg.name}</span>
          ${ts}
        </div>
        <div class="msg-body">${parsedBody}</div>
      </div>
    `;
  });

  html += `</div></div>`;
  return html;
}

export async function exportPDF(docHTML, options) {
  const fullHTML = getPreviewStyles() + docHTML;
  const container = document.createElement('div');
  container.id = 'pdf-container';
  container.innerHTML = fullHTML;
  // Use visibility rendering instead of moving offscreen
  container.style.cssText = 'position:absolute;top:0;left:0;opacity:0;pointer-events:none;z-index:-100;width:794px;padding:40px;font-family:Inter,sans-serif;background-color:' + getThemeBG(options.theme);
  
  document.body.appendChild(container);

  const fmtMap = { a4: 'a4', letter: [215.9, 279.4], legal: [215.9, 355.6] };

  try {
    if (window.html2pdf) {
      await window.html2pdf().set({
        margin:      [15, 15, 20, 15],
        filename:    'chatexport-pro.pdf',
        image:       { type: 'jpeg', quality: 0.97 },
        html2canvas: { scale: 2, useCORS: true, logging: false, backgroundColor: getThemeBG(options.theme), windowWidth: 794 },
        jsPDF:       { unit: 'mm', format: fmtMap[options.pageSize] || 'a4', orientation: 'portrait' },
        pagebreak:   { mode: ['avoid-all', 'css', 'legacy'] },
      }).from(container).save();
    }
  } finally {
    document.body.removeChild(container);
  }
}

export function exportDOCX(docHTML) {
  const full = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>AI Conversation</title>
<style>
  body { font-family: Arial, sans-serif; font-size: 11pt; color: #000; }
  h1, h2, h3 { font-family: Arial, sans-serif; color: #111; }
  .msg-block { margin-bottom: 24px; padding-bottom: 12px; border-bottom: 1px solid #ccc; }
  .msg-header { font-weight: bold; font-size: 14pt; margin-bottom: 8px; color: #000; }
  .msg-meta { font-size: 9pt; color: #666; margin-left: 8px; font-weight: normal; }
  pre { background-color: #f4f4f4; padding: 10px; border: 1px solid #ddd; font-family: "Courier New", Courier, monospace; }
  code { font-family: "Courier New", Courier, monospace; background-color: #f9f9f9; padding: 2px 4px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
  th, td { border: 1px solid #999; padding: 8px; text-align: left; }
  th { background-color: #eee; }
  blockquote { margin-left: 10px; padding-left: 10px; border-left: 3px solid #6c63ff; color: #333; }
</style>
</head>
<body>
${docHTML}
</body>
</html>`;
  
  if (typeof window.htmlDocx === 'undefined') {
    alert("DOCX conversion library failed to load.");
    return;
  }
  const converted = window.htmlDocx.asBlob(full);
  downloadFile('chatexport-pro.docx', converted, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', true);
}

export function exportMarkdown(messages, options) {
  const now = new Date().toLocaleString();
  const words = messages.reduce((n, m) => n + countWords(m.content), 0);
  let md = `# AI Conversation Export\n\n> Generated by ChatExport Pro on ${now}\n\n`;

  if (options.stats) {
    md += `**Stats:** ${messages.length} messages | ${words.toLocaleString()} words | ~${Math.round(words * 1.33).toLocaleString()} tokens\n\n---\n\n`;
  }

  messages.forEach((msg, i) => {
    if (msg.role === 'system') { md += `> ${msg.content}\n\n`; return; }
    const icon  = msg.role === 'user' ? '👤' : '🤖';
    const ts    = (options.timestamps && msg.timestamp) ? ` *(${msg.timestamp})*` : '';
    md += `## ${icon} ${msg.name}${ts}\n\n${msg.content}\n\n`;
    if (i < messages.length - 1) md += `---\n\n`;
  });

  downloadFile('chatexport-pro.md', md, 'text/markdown');
}

export function exportHTML(docHTML) {
  const full = `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Conversation — ChatExport Pro</title>
${getPreviewStyles()}
<style>body{font-family:'Inter',sans-serif;background:#f6f6fb;padding:40px 20px}
.wrapper{max-width:800px;margin:0 auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 4px 24px rgba(0,0,0,.08)}
.export-footer{text-align:center;margin-top:40px;font-size:.78rem;color:#aaa}</style>
</head><body>
<div class="wrapper">
${docHTML}
<div class="export-footer">Exported by ChatExport Pro</div>
</div></body></html>`;
  downloadFile('chatexport-pro.html', full, 'text/html');
}

function downloadFile(filename, content, mimeType, isBlob = false) {
  const blob = isBlob ? content : new Blob([content], { type: mimeType + ';charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename });
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
